# -*- coding: utf-8 -*-
"""bikesharing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1klehHR0s_ahEOrUhKxpTUFU7z9UMVY_I

# Proyek Analisis Data: Bike Sharing

#Nama : Laras Itra Dini
Email : larasitradini01@gmail.com

#Pertanyaan Bisnis
1. Bagaimana pengaruh cuaca pada saat musim gugur terhapa penggunaan casual?

2. Bagaimana pengaruh suhu terhadap pengguna terdaftar?

# Library Yang dibutuhkan
"""

# Import ibrary
import pandas as pd
import plotly.express as px

import warnings

"""#Data Wraggling

#Gathering Data
"""

df_day = pd.read_csv("day.csv")
df_hour = pd.read_csv("hour.csv")

df_day.head()

df_hour.head()

"""#Assesing Data

# >Data Type
"""

print('Dataframe day:')
print(df_day.info())

print('\nDataframe hour:')
print(df_hour.info())

"""#Missing Value"""

print('Dataframe day:')
print(df_day.isna().sum())

print('\nDataframe hour:')
print(df_hour.isna().sum())

"""# Duplicate Data"""

print('Dataframe day:', df_day.duplicated().sum())
print("Dataframe hour:", df_hour.duplicated().sum())

"""# Descriptive Statistic"""

df_day.describe()

df_hour.describe()

"""# Cleaning Data"""

# df_day
df_day["dteday"] = pd.to_datetime(df_day["dteday"])
# df_hour
df_hour["dteday"] = pd.to_datetime(df_hour["dteday"])

# Check data type for df_day and df_hour
print('df_day["dteday"] : ', df_day["dteday"].dtypes)
print('df_hour["dteday"] : ', df_hour["dteday"].dtypes)

"""# Exploratory Data Analysis (EDA)"""

warnings.filterwarnings("ignore")

# df_day
correlation_matrix = df_day.corr()
fig = px.imshow(correlation_matrix)
fig.update_layout(title="Korelasi antara Variabel Numerik")
fig.show()

"""# Distribusi variabel numerik"""

numeric_cols = ['temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']
for col in numeric_cols:
    fig = px.histogram(df_day, x=col, title=f'Distribusi {col}')
    fig.show()

"""#Distribusi variabel kategorikal"""

categorical_cols = ['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday', 'weathersit']
for col in categorical_cols:
    fig = px.bar(df_day[col].value_counts().reset_index(), x='index', y=col)
    fig.update_layout(title=f'Distribusi {col}')
    fig.show()

"""#Hubungan Musim Dengan Jumlah Sewa"""

fig = px.box(df_day, x='season', y='cnt')
fig.update_layout(title='Hubungan antara Musim dan Jumlah Sewa')
fig.show()

"""#Hubungan Hari Libur Dengan Jumlah Sewa"""

fig = px.box(df_day, x='holiday', y='cnt')
fig.update_layout(title='Hubungan antara Hari Libur dan Jumlah Sewa')
fig.show()

"""#Hubungan Cuaca dengan jumlah sewa"""

fig = px.box(df_day, x='weathersit', y='cnt')
fig.update_layout(title='Hubungan antara Cuaca dan Jumlah Sewa')
fig.show()

"""#Hubungan suhu dengan jumlah sewa"""

fig = px.scatter(df_day, x='temp', y='cnt', title='Scatter Plot antara Suhu dan Jumlah Sewa')
fig.show()

"""#Jumlah penyewa sepeda pada hari libur"""

# Filter tahun 2012 dan musim gugur (season 3)
filtered_data = df_day[(df_day["yr"] == 1) & (df_day["season"] == 3)]

# Hitung jumlah total sewa sepeda (cnt)
total_sewa_sepeda = filtered_data["cnt"].sum()

print("Jumlah total sewa sepeda untuk tahun 2012 selama musim gugur (musim 3):", total_sewa_sepeda)

"""#Cara meningkatkan pengguna sepeda pada hari kerja"""

# Filter pengguna casual (casual) pada hari kerja (workingday = 1)
filtered_data = df_day[(df_day["workingday"] == 1) & (df_day["casual"] > 0)]

# Visualisasikan jumlah sewa sepeda casual pada hari kerja
fig = px.bar(filtered_data, x="weekday", y="casual", title="Jumlah Sewa Sepeda Casual pada Hari Kerja")
fig.update_xaxes(title="Hari Kerja")
fig.update_yaxes(title="Jumlah Sewa Sepeda Casual")
fig.show()

"""# Pertanyaan 1

Bagaimana pengaruh cuaca pada saat musim gugur terhapa penggunaan casual?
"""

# Filter musim gugur (season 3)
filtered_data = df_day[df_day["season"] == 3]

# Plot untuk menganalisis pengaruh cuaca terhadap jumlah sewa sepeda
fig = px.bar(filtered_data, x="weathersit", y="cnt", title="Pengaruh Cuaca terhadap Jumlah Sewa Sepeda (Musim Gugur)")
fig.update_xaxes(title="Cuaca (weathersit)")
fig.update_yaxes(title="Jumlah Sewa Sepeda (cnt)")

# Tampilkan plot
fig.show()

"""kesimpulan:
Dari analisis grafik yang telah dilakukan, kita dapat menyimpulkan bahwa kondisi cuaca memiliki dampak yang signifikan terhadap jumlah sepeda yang disewa. Grafik tersebut menunjukkan bahwa variasi dalam kondisi cuaca berkontribusi secara nyata pada perilaku pengguna sepeda. Secara lebih khusus, kita dapat mengamati bahwa pada kondisi cuaca tertentu, seperti cuaca cerah atau sebagian berawan (weathersit 1), terjadi peningkatan yang cukup besar dalam jumlah sepeda yang disewa.

Analisis ini menyarankan bahwa elemen-elemen seperti cuaca dapat menjadi faktor penting yang perlu diperhitungkan oleh penyedia layanan sewa sepeda, karena mampu memengaruhi tingkat permintaan sepeda. Informasi ini juga dapat memberikan wawasan berharga kepada para pengambil keputusan dalam perencanaan stok sepeda, penyesuaian tarif, atau pengembangan strategi pemasaran yang lebih efektif, terutama berdasarkan fluktuasi kondisi cuaca.

# Pertanyaan 2
Bagaimana pengaruh suhu terhadap pengguna terdaftar?
"""

# Hubungan suhu (temp) dengan jumlah pengguna terdaftar (registered)
fig = px.scatter(df_day, x="temp", y="registered", title="Hubungan Suhu dengan Jumlah Pengguna Terdaftar")
fig.update_xaxes(title="Suhu (temp)")
fig.update_yaxes(title="Jumlah Pengguna Terdaftar")
fig.show()

"""kesimpulan:
Grafik menunjukkan adanya hubungan positif, yang menunjukkan bahwa peningkatan suhu juga berdampak pada peningkatan jumlah pengguna yang terdaftar.





"""